openapi: 3.0.3
info:
  title: Cosmos Swagger
  description: |-
    This is a list of all APIs available in the Cosmos backend
  termsOfService: http://swagger.io/terms/
  contact:
    email: cosmos.social.time@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-beta001
servers:
  - url: http://18.222.112.130:8080/api
tags:
  - name: admin
    description: All APIs related to admin
  - name: auth
    description: All APIs related to authentication
  - name: dashboard
    description: All APIs related to authentication
paths:
  # ADMIN
  /admin/modifyUserRole:
    patch:
      tags:
        - admin
      summary: Changes user role
      description: Allows ADMINS to change another user role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  example: 1
                role:
                  type: string
                  enum:
                    - admin
                    - user
        required: true
      responses:
        '200':
          description: Role updated successfully
        '400':
          description: User not found
        '500':
          description: Internal server error
      security:
        - bearer_token: []

  # AUTH
  /auth/signup:
    post:
      tags:
        - auth
      summary: Creates a new user account
      description: Creates a new user and send an email to the user with a confirmation link
      operationId: updatePet
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              required:
                - byname
                - fullName
                - email
                - password
                - passwordConfirmation
              properties:
                byname:
                  type: string
                  example: João
                fullName:
                  type: string
                  example: João da Silva Fernandes
                email:
                  type: string
                  format: "email"
                password:
                  type: string
                  format: "password"
                  example: "SenhaForte1!"
                passwordConfirmation:
                  type: string
                  format: "password"
                  example: "SenhaForte1!"
        required: true
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: "User ID"
                    example: 1
        '400':
          description: Invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
  /auth/signin:
    post:
      tags:
        - "auth"
      summary: "Authenticates the user"
      description: "Authenticate the user returning a bearer token"
      operationId: "signIn"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: "email"
                password:
                  type: string
                  format: "password"
                  example: "SenhaForte1!"
        required: true
      responses:
        '200':
          description: User authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: "Bearer Token"
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgxOTQ5ODE1LCJleHAiOjE2ODE5NTM0MTV9.m3lkgvjS3e8MqZjUlG-Mplku4VAze1vPNFSJkX5CFiQ"
        '401':
          description: Invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
  /auth/verifyUser:
    patch:
      tags:
        - auth
      summary: Confirm user account
      description: Confirms that user clicked in the confirmation link recieved on the email
      operationId: verifyuserAccount
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - token
              properties:
                email:
                  type: string
                  format: "email"
                token:
                  type: string
                  example: "f5f69931faba6b8e3258d0b1c4027fa1e725cf2f87ac1b1f539e2442b5793a12"
        required: true
      responses:
        '200':
          description: User verified successfully
        '403':
          description: Token is invalid
  /auth/resendVerification:
    patch:
      tags:
        - auth
      summary: Resend verification email
      operationId: resendVerification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
        required: true
      responses:
        '200':
          description: Email sent successfully
        '204':
          description: User is already verified
        '400':
          description: Email not registered
        '500':
          description: Internal server error
  /auth/resetPassword:
    patch:
      tags:
        - auth
      summary: Change user password
      operationId: resetPassword
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - token
              properties:
                email:
                  type: string
                  format: "email"
                password:
                  type: string
                  format: password
                  example: "SenhaForte1!"
                token:
                  type: string
                  example: "f5f69931faba6b8e3258d0b1c4027fa1e725cf2f87ac1b1f539e2442b5793a12"
        required: true
      responses:
        '200':
          description: Password updated successfully
        '400':
          description: Email not registered
        '403':
          description: Token invalid
        '500':
          description: Internal server error
  /auth/forgotPassword:
    patch:
      tags:
        - auth
      summary: Send a forgot password email to user
      operationId: forgotPassword
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
        required: true
      responses:
        '200':
          description: Email sent successfully
        '400':
          description: User not registered
        '500':
          description: Internal server error

  # DASHBOARD
  /dashboard:
    get:
      tags:
        - dashboard
      summary: Returns user dashboard info
      description: Returns user dashboard info based on type of user (ex. Admin, Volunteer, ONG Director, etc.)
      responses:
        '200':
          description: Operation successfull
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/VolunteerDashboard'
      security:
        - bearer_token: []
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: "Message describing the error"
    Program:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: 'Itau Social para Educação 2.0'
        description:
          type: string
          example: 'Essa é uma campanha do Itau Social visando ajudar as causas de educação para crianças carentes'
        startDate:
          type: string
          format: date
          example: '2023-04-23'
        endDate:
          type: string
          format: date
          example: '2024-04-23'
    Storage:
      type: object
      properties:
        id:
          type: number
          example: 1
        bucketName:
          type: string
          example: 'userBanners'
        directoryPath:
          type: string
          example: 'path/to/file.jpeg'
        mimeType:
          type: string
          example: 'image/jpeg'
    UserAchievements:
      type: array
      description: 'Will have all achievements avalaible in the database. Flags if the user has completed it by the "completed" key'
      items:
        type: object
        properties:
          id:
            type: number
            example: 1
          achievement:
            type: string
            example: 'first_application'
          completed:
            type: boolean
            example: false
    UserSecureData:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          format: email
        isVerified:
          type: boolean
        byname:
          type: string
          example: "João"
        fullName:
          type: string
          example: "João da Silva Fernandes"
        gender:
          type: string
          example: 'Masculino'
        birthdate:
          type: string
          format: date
          example: '1982-01-01'
        country:
          type: string
          example: 'Brasil'
        state:
          type: string
          example: 'SP'
        city:
          type: string
          example: 'Carapicuiba'
        professionalExperience:
          type: number
          example: 10.6
        professionalSector:
          type: string
          example: 'Finanças'
        professionalRole:
          type: string
          example: 'Bancário'
        availableTime:
          type: number
          example: 4
        linkedinUrl:
          type: string
          example: 'https://linkedin.com/in/joaodasilvafernandes1323'
        professionalPreviousExperiences:
          type: string
          example: |-
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Aliquam tempor massa diam, et fringilla enim sollicitudin ac.
            Aliquam at lectus facilisis, varius nisl semper, dapibus massa
        mainCompetencies:
          type: string
          example: 'Sou ótimo com números'
        reasonToJoin:
          type: string
          example: 'Sou caridoso'
        previousMentorship:
          type: string
          example: 'Nunca fiz nada assim antes'
        profilePicture:
          $ref: '#/components/schemas/Storage'
        banner:
          $ref: '#/components/schemas/Storage'
    VolunteerDashboard:
      type: object
      properties:
        achievements:
          $ref: '#/components/schemas/UserAchievements'
        programs:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Program'
              - type: object
                properties:
                  applied:
                    type: boolean
                    example: true
        user:
          $ref: '#/components/schemas/UserSecureData'
  securitySchemes:
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT